-- CASE//ZERO combined content + analytics update
-- Safe to run more than once.

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_name text not null,
  case_id text,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_user_id_idx on public.analytics_events(user_id);
create index if not exists analytics_events_event_name_idx on public.analytics_events(event_name);
create index if not exists analytics_events_case_id_idx on public.analytics_events(case_id);
create index if not exists analytics_events_created_at_idx on public.analytics_events(created_at desc);

alter table public.analytics_events enable row level security;

drop policy if exists "Users can insert own analytics" on public.analytics_events;
create policy "Users can insert own analytics"
on public.analytics_events for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can read own analytics" on public.analytics_events;
create policy "Users can read own analytics"
on public.analytics_events for select
to authenticated
using (auth.uid() = user_id);

grant usage on schema public to authenticated;
grant select, insert on table public.analytics_events to authenticated;
grant usage, select on sequence public.analytics_events_id_seq to authenticated;

notify pgrst, 'reload schema';
